# Generated by Django 3.0.3 on 2020-09-21 06:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BbsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('regdate', models.DateTimeField(default=datetime.datetime(2020, 9, 21, 6, 12, 36, 993660, tzinfo=utc))),
                ('viewcnt', models.IntegerField()),
            ],
        ),
    ]
