# Generated by Django 3.0.3 on 2020-09-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BbsApp', '0003_auto_20200921_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='viewcnt',
            field=models.IntegerField(default=0),
        ),
    ]
